apiVersion: v1
kind: PersistentVolume
metadata:
  name: cr-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/shared/cr-mysql-data'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cr-wordpress-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/shared/cr-wp-data'

    