apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cr-mysql-pvc
  namespace: chrissyroshak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cr-pvc
  namespace: chrissyroshak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

