apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-wordpress
  namespace: chrissyroshak
  labels:
    app: cr-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-wordpress
  template:
    metadata:
      labels:
        app: cr-wordpress
    spec:
      containers:
        - name: cr-wordpress-container
          image: wordpress:6.3.1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html/wp-content
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: php-config
              subPath: uploads.ini
            - name: wp-maintenance-mode
              mountPath: /var/www/html/wp-content/plugins/wp-maintenance-mode
  #          - mountPath: /var/www/html/.htaccess
  #            name: wp-htaccess
  #            subPath: .htaccess



          env:
            - name: WORDPRESS_DB_HOST
              value: cr-mysql-service:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DEBUG
              value: "true" 
            - name: PHP_MEMORY_LIMIT
              value: 2048M
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_MEMORY_LIMIT', '2048M');
                #define('WP_ALLOW_MULTISITE', true);
                #define( 'MULTISITE', true );
                #define( 'SUBDOMAIN_INSTALL', true );
                #define( 'DOMAIN_CURRENT_SITE', 'chrissyroshak.com' );
                #define( 'PATH_CURRENT_SITE', '/' );
                #define( 'SITE_ID_CURRENT_SITE', 1 );
                #define( 'BLOG_ID_CURRENT_SITE', 1 );
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "chown -R www-data:www-data /var/www; chmod -R 774 /var/www"]                        
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: cr-pvc
        - configMap:
            defaultMode: 420
            name: wp-php-config
          name: php-config
        - name: wp-maintenance-mode
          hostPath: 
            path: /home/microshak/Source/lab/ChrissyRoshak/plugins/wp-maintenance-mode


#        - configMap:
#            defaultMode: 0777
#            name: wp-htaccess
#          name: wp-htaccess
          



