apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-ff1-dev
  namespace: chrissyroshak
spec:
  secretName: wordpress-ff1-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - chrissyroshak.com

    