dashboard:
 enabled: true
 domain: traefik.microshak.com
rbac:
 enabled: true

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false
rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.0.240 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []