apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wordpress
  namespace: demo-wordpress
  labels:
    app: demo-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-wordpress
  template:
    metadata:
      labels:
        app: demo-wordpress
    spec:
      containers:
        - name: demo-wordpress-container
          image: wordpress:6.1.1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '3Gi'
              cpu: '3'
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html/wp-content
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: php-config
              subPath: uploads.ini
  #          - mountPath: /var/www/html/.htaccess
  #            name: wp-htaccess
  #            subPath: .htaccess



          env:
            - name: WORDPRESS_DB_HOST
              value: demo-mysql-service:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DEBUG
              value: "true" 
            - name: PHP_MEMORY_LIMIT
              value: 2048M
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_MEMORY_LIMIT', '2048M');
                #define('WP_ALLOW_MULTISITE', true);
                #define( 'MULTISITE', true );
                #define( 'SUBDOMAIN_INSTALL', true );
                #define( 'DOMAIN_CURRENT_SITE', 'chrissyroshak.com' );
                #define( 'PATH_CURRENT_SITE', '/' );
                #define( 'SITE_ID_CURRENT_SITE', 1 );
                #define( 'BLOG_ID_CURRENT_SITE', 1 );
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "chown -R www-data:www-data /var/www; chmod -R 774 /var/www; chmod 644 .htaccess;","chmod 644 /var/www/html/wp-content/uploads/wpforms/.htaccess;","chmod 644 /var/www/html/wp-content/plugins/akismet/.htaccess;", "chmod 644 var/www/html/wp-content/uploads/wpseo-redirects/.htaccess;", "chmod 644 /usr/src/wordpress/.htaccess;", "chmod -R 755 /var/www/html"]                        
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: demo-wordpress-pvc
        - configMap:
            defaultMode: 420
            name: wp-php-config
          name: php-config
 #       - configMap:
 #           defaultMode: 0755
 #           name: wp-htaccess
 #         name: wp-htaccess
          



