apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wordpress
  namespace: demo-wordpress
  labels:
    app: demo-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-wordpress
  template:
    metadata:
      labels:
        app: demo-wordpress
    spec:
      containers:
        - name: demo-wordpress-container
          image: wordpress:6.1.1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html/wp-content
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: php-config
              subPath: uploads.ini
          env:
            - name: WORDPRESS_DB_HOST
              value: demo-mysql-service:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DEBUG
              value: "true" 
            - name: PHP_MEMORY_LIMIT
              value: 2048M
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_MEMORY_LIMIT', '2048M');
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "chown -R www-data:www-data /var/www; chmod -R 774 /var/www"]                        
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: demo-wordpress-pvc
        - configMap:
            defaultMode: 420
            name: wp-php-config
          name: php-config


