version:                "3"
services:
    datascience-notebook:
        image:            .
        restart: unless-stopped
        volumes:
        - ./notebooks:/home/jovyan/work2
        - ./Code:/home/jovyan/work
        ports:
        - 8888:8888
        command: "jupyter lab --allow-root   --user root -w /home/jovyan/ --ip=0.0.0.0 --no-browser -e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R'  --NotebookApp.notebook_dir='work' --NotebookApp.token='' "
        container_name:   connect-notebook
